Multi-driver support and resorces usage
KiruhaNovikov/ParkMeTesting pull request #3
Opened 2017-07-24 13:57 UTC by Answeroid

Added multiple driver support and created resources directlry to conrinue working with them. Need some advice how to organize usage od that resources in code&

2017-07-25 15:20 UTC, Answeroid commented
Кароч, напишу на русском :)
Все тут наверчено так как я много времени потратил на настройку дженкинса, авс инстанса и прочую хурму, разбирался с синтаксисом джавы и все такое. Пока имейлы не шлются но мне влом дофиксить ейчас.
У меня много вопросов по коду что я закоммитил.
Синглон из драйвера сделал, дохуя всего там напилил по коду и теперь осталось имхо только PageFactory реализовать и можно будет педалить тестики. @boshasiv плиз посмотри этот огромнейший пул реквест и постарайся не выпиливать его по причине большого кол-ва коммитов (((

2017-07-26 09:10 UTC, boshasiv requested changes
Overall - let's try to separate changes... Multi-driver and resources are unrelated changes, so I assume that it should be 2 separate pull requests

2017-07-26 09:10 UTC, boshasiv commented on src/main/java/DriverBuilder.java
> +        } else{
Should be some driver by default

2017-07-26 09:10 UTC, boshasiv commented on src/main/java/HomePage.java
> +        Config.loadProperties("HomePage.properties");
We will not use properties for describing page elements locators. Let's use FindBy annotation instead and PageFactory.initElements(...) for instantiating page object

2017-07-26 15:05 UTC, Answeroid commented on src/main/java/DriverBuilder.java
> +        } else{
fixed. Will arrive in next commit

2017-07-26 15:10 UTC, Answeroid commented on src/main/java/HomePage.java
> +        Config.loadProperties("HomePage.properties");
page object and page factory usage will be in the next pull request separately

2017-07-30 16:30 UTC, merged